### ISSUE TITLE
Improve error handling for bad data on the back end

### ISSUE THREAD

**Issue by finnhodgkin** [ZooeyMiller/big-issue-candidate-email#28]
Particularly in getCandidates.js and postmark.js there is very limited error handling for incorrect API responses.

**Comment by finnhodgkin** [comment]
api.js is missing a .catch. If the user inputs a bad postcode the app stops.

**Comment by finnhodgkin** [comment]
apiSendEmail.js has a .catch that directly passes the error to the frontend - reply(error).

Not ideal for security...

**Comment by ZooeyMiller** [comment]
The error handling in getCandidates.js actually turns out to be fine, it's more on the front end when we make a GET req to the /api route.

It's to do with the way that fetch deals with status codes. fetch does not reject the promise when the status code is 200, so when you get the res from the request you need to check status code, throw and error if it is not 200, then catch that error in the promise chain.
